# Geschwindigkeit - nicht kleiner 80 stellen, sonst zählt man zu viel mit
WPM = 80

# Faktor von 1.0 entspricht dem Standard. Zum Lernen kann der Abstand von Zeichen und Wörtern erhöht werden. Der Abstand innerhalb der Zeichen entspricht immer WPM.
CharacterSpacingFactor = 3
WordSpacingFactor = 3

# Zu benutzende Zeichen
Characters = "ACDEINOQRSTUX4590"
CharacterCount = 100

# Für Intensiv-Training können hier Zeichen angegeben werden, die verstärkt geübt werden sollen
IntensiveCharacters = "4U"
IntensiveFactor = 5

# Ton Einstellungen
Frequency1 = 700
Frequency2 = 700
# Das kleiner als Eins stellen, wenn man Knarzen auf dem Lautsprecher hat
Volume = 0.25